# Generated by Django 5.1 on 2024-08-31 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=155)),
                ('avatar', models.ImageField(default='./Profile_Images/default_profile.JPG', upload_to='./Profile_Images')),
                ('preferences', models.CharField(choices=[('work', 'work'), ('Gamer', 'Gamer'), ('miner', 'miner')], max_length=15)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
