# Generated by Django 5.1 on 2024-09-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_profile.JPG', upload_to='Profile_Images'),
        ),
    ]
